# https://wei.github.io/pull/
version: "1"
rules:
  - base: master
    upstream: wei:master
    mergeMethod: hardreset

label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict
