# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  # name: .github
  # A short description of the repository that will show up on GitHub
  description: ":atom: Repository used to organize everything around Organisations."
  # A URL with more information about the repository
  # homepage:
  # A comma-separated list of topics to set on the repository
  topics: ivank, github, configuration, sync, org, organisation

  # Either `true` to make the repository private, or `false` to make it public.
  private: false
  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true
  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false
  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false
  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: false
  # Updates the default branch for this repository.
  default_branch: main
  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true
  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true
  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true
  # Either `true` to enable automatic deletion of branches on merge, or `false` to disable
  delete_branch_on_merge: true
  # Either `true` to enable automated security fixes, or `false` to disable
  # automated security fixes.
  enable_automated_security_fixes: true
  # Either `true` to enable vulnerability alerts, or `false` to disable
  # vulnerability alerts.
  enable_vulnerability_alerts: false

branches:
- name: main
  protection:
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
    required_status_checks:
      strict: true
      contexts: []
    enforce_admins: false


# Labels: define labels for Issues and Pull Requests
labels:
- name: bug
  color: CC0000
  description: An issue with the system 🐛.
- name: feature
  color: '#336699'
  description: New functionality.
- name: good first issue
  color: 7057ff
- name: hackathon
  color: 85f920
- name: help wanted
  color: 008672
- name: question
  color: D876E3
- name: wontfix
  color: FFFFFF
- name: duplicate
  color: CFD3D7
- name: bug
  color: D73A4A
- name: documentation
  color: 0e8a16
  description: A PR that adds to documentation - used by Release Drafter
- name: hacktoberfest
  color: bdff3a
  description: 'Hacktoberfest. https://jenkins.io/blog/2018/10/01/hacktoberfest/'
- name: feature
  color: 1d00ff
  description: A PR that adds a feature - used by Release Drafter
- name: bugfix
  oldname: fix
  color: c9e85c
  description: A PR that fixes a bug - used by Release Drafter
- name: chore
  color: c9abea
  description: a PR that adds to maintenance - used by Release Drafter
- name: test
  color: d6e819
  description: A PR that adds to testing - used by Release Drafter
- name: pinned
  color: 5ed5e5
  description: 'Used to avoid stale[bot] marking a issue/PR stale'
- name: plugin-compatibility
  color: 8425c4
- name: stale
  color: ffffff
  description: 'Used by stale[bot] to mark a issue/PR stale'
- name: skip-changelog
  color: f44271
  description: A PR that is excluded from Release draft - used by Release Drafter
- name: removed
  color: aa0f1c
  description: A PR that removes code - used by Release Drafter
- name: deprecated
  color: e2b626
  description: A PR that deprecates code - used by Release Drafter
- name: breaking
  color: 640910
  description: A PR that is a breaking change - used by Release Drafter
- name: dev-tools
  color: 551a8b
  description: JCasC Community Bridge Dev-Tools Project
- name: dependencies
  color: 0366d6
  description: A PR that updates dependencies - used by Release Drafter
- name: release
  color: 640910
  description: A PR that updates dependencies - used by Release Drafter
# Format and labels used aim to match those used by Ansible project
# https://github.com/marketplace/actions/github-labeler
- name: deprecated
  color: "fef2c0"
  description: "This issue/PR relates to a deprecated module."
- name: feature
  color: "006b75"
  description: "This issue/PR relates to a feature request."
- name: major
  color: "c6476b"
  description: "Marks an important and likely breaking change."
- name: packaging
  color: "4071a5"
  description: "Packaging category"
- name: performance
  color: "555555"
  description: "Relates to product or testing performance."
- name: skip-changelog
  color: "eeeeee"
  description: "Can be missed from the changelog."
- name: stale
  color: "eeeeee"
  description: "Not updated in long time, will be closed soon."
- name: test
  color: "0e8a16"
  description: "This PR relates to tests, QA, CI."
- name: gate
  color: "41b6e6"
  description: "Gate PR in Zuul CI"
## more info https://github.com/crazy-max/ghaction-github-labeler
- # automerge
  name: ":bell: automerge"
  color: "8f4fbc"
  description: ""
- # approve
  name: ":bell: approved"
  color: "8f4fbc"
  description: ""
- # bot
  name: ":robot: bot"
  color: "69cde9"
  description: ""
- # automation
  name: ":robot: ci"
  color: "69cde9"
  description: ""
- # bug
  name: ":bug: bug"
  color: "b60205"
  description: "This issue/PR relates to a bug."
- # dependencies
  name: ":game_die: dependencies"
  color: "0366d6"
  description: ""
- # documentation
  name: ":memo: documentation"
  color: "c5def5"
  description: "This issue/PR relates to or includes documentation."
- name: ":memo: docs"
  color: "4071a5"
  description: "This issue/PR relates to or includes documentation."
- # duplicate
  name: ":busts_in_silhouette: duplicate"
  color: "cccccc"
  description: ""
- # enhancement
  name: ":sparkles: enhancement"
  color: "0054ca"
  description: "This issue/PR relates to a feature request."
- # feature request
  name: ":bulb: feature request"
  color: "0e8a16"
  description: ""
- # feedback
  name: ":mega: feedback"
  color: "03a9f4"
  description: ""
- # future maybe
  name: ":rocket: future maybe"
  color: "fef2c0"
  description: ""
- # good first issue
  name: ":hatching_chick: good first issue"
  color: "7057ff"
  description: ""
- # help wanted
  name: ":pray: help wanted"
  color: "4caf50"
  description: ""
- # invalid
  name: ":no_entry_sign: invalid"
  color: "e6e6e6"
  description: ""
- # investigate
  name: ":mag: investigate"
  color: "e6625b"
  description: ""
- # needs more info
  name: ":thinking: needs more info"
  color: "795548"
  description: ""
- # pinned
  name: ":pushpin: pinned"
  color: "28008e"
  description: ""
- # question
  name: ":question: question"
  color: "3f51b5"
  description: ""
- # sponsor
  name: ":sparkling_heart: sponsor"
  color: "fedbf0"
  description: ""
- # stale
  name: ":skull: stale"
  color: "237da0"
  description: ""
- # upstream
  name: ":eyes: upstream"
  color: "fbca04"
  description: ""
- # wontfix
  name: ":coffin: wontfix"
  color: "ffffff"
  description: ""
# commit sizes
- # size s
  name: ":smiley_cat: size S"
  color: "ffffff"
  description: ""
- # size M
  name: ":nauseated_face: size M"
  color: "ffffff"
  description: ""
- # size L
  name: ":skull_and_crossbones: size L"
  color: "ffffff"
  description: ""
# Kind
- color: e7e9eb
  name: kind/bug
  description: Something isn't working
- color: e7e9eb
  name: kind/feature
  description: New feature request
- color: e7e9eb
  name: kind/question
  description: Generic question
- color: e7e9eb
  name: kind/chore
  description: Non feature change
- color: e7e9eb
  name: kind/fix
  description: Fix a bug
- color: e7e9eb
  name: kind/docs
  description: Non feature documentation change
- color: e7e9eb
  name: kind/refactor
  description: Non feature refactor change
- color: e7e9eb
  name: kind/dependencies
  description: Pull requests that update a dependency file

# Priority
- color: d93f0b
  name: priority/urgent-now
  description: Urgent fix, as fast as possible
- color: d93f0b
  name: priority/important-soon
  description: Will be important soon

# Triage
- color: b1f488
  name: triage/accepted
  description: Triage has been accepted

# Operating system
- color: 0d1d49
  name: os/win
- color: 0d1d49
  name: os/linux
- color: 0d1d49
  name: os/mac

# TODO
- name: 'todo :spiral_notepad:'
  color: 00B0D8
# https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md
# https://github.com/DeFiCh/oss-governance-bot/blob/main/.github/labels.yml
