blank_issues_enabled: true
contact_links:
  - name: "\U0001F914 All other questions, including if you're not sure what to do."
    url: https://discourse.jupyter.org
    about: Search on Discourse for similar questions or ask for help there.
  - name: "Help"
    about: "The issue tracker is only meant for bug reports, feature/plugin requests and plugin issues. Please ask your questions on the discussions forum and look for already existing answers."
    url: https://ivankatliarchuk.github.io/
