# @todo: sync with other repositories
---
name: auto-merge
on:
  pull_request_review: { types: submitted }
  pull_request_target:
    branches: [$default-branch]
    types: [ready_for_review, labeled, unlabeled]
  check_suite:
    types:
      - completed
  status: {}
  # Try merging the specified pull request or all open pull requests if none is specified.
  workflow_dispatch:
    inputs:
      pull-request:
        description: pull request number
        required: false

jobs:
  automerge:
    if: github.event.review.state == 'approved' || !github.event.review
    runs-on: ubuntu-latest
    steps:

      - name: sleep
        run: sleep 30

      - name: automerge
        uses: pascalgn/automerge-action@v0.13.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: 'auto-merge,!wip,!work in progress,!do-not-merge,approved,:bell: automerge,:bell: approved,✅ Approved'
          MERGE_RETRY_SLEEP: "60000"
          MERGE_DELETE_BRANCH: "true"
          MERGE_METHOD: squash


      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: rebase
          required-labels: 'auto-merge,!wip,!work in progress,,approved,:bell: automerge,:bell: approved,✅ Approved'
          do-not-merge-labels: ':warning: do-not-merge,:warning: wip'
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: true
