# @todo: sync with other repositories
---
name: automerge
on:
  pull_request_target:
    branches: [$default-branch]
    types: [synchronize, opened, labeled, unlabeled]
  pull_request:
    types: [synchronize, labeled, unlabeled]
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: 'auto-merge,!wip,!work in progress,!do-not-merge,approved,:bell: automerge,:bell: approved,✅ Approved'
          MERGE_RETRY_SLEEP: "60000"
          MERGE_DELETE_BRANCH: "true"
          MERGE_METHOD: squash
