---
name: governance-labeller

on:
  pull_request_target:
    branches: [master, main]
    types: [synchronize, opened, labeled, unlabeled]
  workflow_dispatch:

jobs:
# https://github.com/marketplace/actions/multi-labeler
  labels-everything:
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}} # optional, default to '${{ github.token }}'
          config-path: .github/labeler.yml # optional, default to '.github/labeler.yml'
