
name: pull request branch labels

on:
  pull_request:
    types:
      - opened

jobs:
  pr-labeler:

    name: Pull Request Labels
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' || github.actor != 'dependabot-preview[bot]'

    steps:

      - uses: thollander/actions-comment-pull-request@1.0.1
        name: leave a comment about our branch naming convention
        # if: ${{ steps.labeller.outputs.applied == 0 }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            **Pro Tip!**
            You can help us label your Pull Requests by using the following branch naming convention next time you create a pull request.
            Branch naming convention | Label
            ------------------------ | ------
            `feature/**`             | kind/feature
            `fix/**`                  | kind/fix
            `chore/**`               | kind/chore
            `docs/**`                | kind/docs
            <hr>
            If your changes do not fall into any of these categories, don't worry.
            You can just ignore this message in that case! 👀
