name: release-drafter

on:
  push:
    branches: [$default-branch]

jobs:
  draft-a-release:
    runs-on: ubuntu-latest
    if: github.repository == 'ivankatliarchuk/.github'
    steps:
      - uses: release-drafter/release-drafter@v5.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
