name: release-drafter

on:
  push:
    branches: [master,main]

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.repository != 'ivankatliarchuk/.github'
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
