name: renovate
on:
  - push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'

      - name: validate config
        uses: rinchsan/renovate-config-validator@v0.0.2
        with:
          pattern: 'renovate.json
