# @todo: sync with other repositories
name: renovate

on:
  workflow_dispatch:
    branches:
      - $default-branch
  schedule:
    - cron: '0 6 * * *'
  pull_request_target:
    branches:
      - $default-branch
    types:
      - closed

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'

      - name: validate config
        uses: rinchsan/renovate-config-validator@v0.0.2
        with:
          pattern: 'renovate.json'

      - name: run renovate bot
        uses: renovatebot/github-action@v23.44.8
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}

