name: renovate

on:
  workflow_dispatch:
    branches:
      - $default-branch
  schedule:
    - cron: '0 6 * * 5'
  pull_request_target:
    branches:
      - $default-branch
    types:
      - closed

env:
  RENOVATE_CONFIG_FOLDER: .github/renovate
  # RENOVATE_CACHE_DIR: renovate/.cache
  LOG_LEVEL: info
  RENOVATE_BASE_CONFIG_PATH: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    container:
      image: dockerhub-username:docker-image-tag
    if: github.repository == 'ivankatliarchuk/.github'
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: '1'


      - name: "execute-dependency-update"
        # uses: docker://renovate/renovate:31.14-slim
        run: >-
          ls -la
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          USER_NAME: ${{ github.repository_owner }}
          RENOVATE_CONFIG_FILE: ${{ env.RENOVATE_BASE_CONFIG_PATH }}/renovate-config.js
          RENOVATE_REPOSITORY_CONFIG_FILE: ${{ env.RENOVATE_BASE_CONFIG_PATH }}/repositories.json
        # with:
        #   entrypoint: bash
        #   args: -c "/usr/local/bin/renovate"

      # This action is too much of opinionated solution
      # https://github.com/renovatebot/github-action install renovate app
      # - name: run renovate across repositories
      #   uses: renovatebot/github-action@v31.13.1
      #   with:
      #     configurationFile: ${{ env.RENOVATE_CONFIG_FOLDER }}/renovate-config.js
      #     token: ${{ secrets.RENOVATE_TOKEN }}
      #   env:
      #     USER_NAME: ${{ github.repository_owner }}
      #     RENOVATE_CACHE_DIR: ${{ env.RENOVATE_CACHE_DIR }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
