name: renovate

on:
  workflow_dispatch:
    branches:
      - $default-branch
  schedule:
    - cron: '0 6 * * 5'
  pull_request_target:
    branches:
      - $default-branch
    types:
      - closed

env:
  RENOVATE_CONFIG_FOLDER: renovate
  # RENOVATE_CACHE_DIR: renovate/.cache
  LOG_LEVEL: info
  RENOVATE_BASE_CONFIG_PATH: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest

    if: github.repository == 'ivankatliarchuk/.github'
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: '1'

      # This action is too much of opinionated solution
      # https://github.com/renovatebot/github-action install renovate app
      - name: run renovate across repositories
        uses: renovatebot/github-action@v31.19.0
        with:
          configurationFile: renovate/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          USER_NAME: ${{ github.repository_owner }}
          # RENOVATE_CACHE_DIR: ${{ env.RENOVATE_CACHE_DIR }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          LOG_LEVEL: 'debug'
