name: renovate

on:
  workflow_dispatch:
    branches:
      - $default-branch
  schedule:
    - cron: '0 6 * * 5'
  pull_request_target:
    branches:
      - $default-branch
    types:
      - closed

env:
  RENOVATE_CONFIG_FOLDER: .github/renovate
  RENOVATE_CACHE_DIR: .github/renovate/.cache
  LOG_LEVEL: info

jobs:
  renovate:
    runs-on: ubuntu-latest
    if: github.repository == 'ivankatliarchuk/.github'
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: '1'
      - name: run it
        uses: docker://renovate/renovate:31.14-slim
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          USER_NAME: ${{ github.repository_owner }}
          RENOVATE_CONFIG_FILE: ./github-action/renovate-config.js
        with:
          entrypoint: bash
          args: -c "pwd;ls -la"
          # /usr/local/bin/renovate
        # run: >-
        #   echo "TEST"

      # https://github.com/renovatebot/github-action install renovate app
      # - name: run renovate across repositories
      #   uses: renovatebot/github-action@v31.13.1
      #   with:
      #     configurationFile: ${{ env.RENOVATE_CONFIG_FOLDER }}/renovate-config.js
      #     token: ${{ secrets.RENOVATE_TOKEN }}
      #   env:
      #     USER_NAME: ${{ github.repository_owner }}
      #     RENOVATE_CACHE_DIR: ${{ env.RENOVATE_CACHE_DIR }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
