name: syncronize-repository-content

on:
  schedule:
    - cron:  '* * * * *'
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  fetch-repo-info:
    name: extract repository data
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'
          submodules: 'true'

      - name: test repo name
        shell: bash
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo "can we read? $GITHUB_REPOSITORY"
          echo "---"
          env
          echo "---"

  validate-base-pull-configuration:
    name: validate-pull-configuration
    if: github.repository == 'ivankatliarchuk/.github'
    needs: [fetch-repo-info]
    runs-on: ubuntu-latest
    steps:

      - name: test curl
        if: github.repository == 'ivankatliarchuk/.github'
        uses: wei/curl@master
        with:
          args: https://pull.git.ci/check/$GITHUB_REPOSITORY


