name: syncronize-repository-content

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  extract-data:
    name: extract repository data
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'
          submodules: 'true'

      - name: test it
        run: |
          echo ${{ github.repository.name }}
