name: syncronize-repository-content

on:
  schedule:
    - cron:  '* * * * *'
  workflow_dispatch:
  push:
    branches: [main]

env:
  OWNER: ivankatliarchuk

jobs:
  fetch-repo-info:
    name: extract repository data
    runs-on: ubuntu-latest
    steps:
      # Step 1: run a standard checkout action, provided by github
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'
          submodules: 'recursive'

      - name: fetch-repo-name
        shell: bash
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo "can we read? $GITHUB_REPOSITORY"
          echo "---"
          env
          echo "---"

  fork-sync:
    name: fork-sync
    if: github.repository != 'ivankatliarchuk/.github'
    needs: [fetch-repo-info]
    runs-on: ubuntu-latest
    steps:

      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: ${{ env.OWNER }}
          base: main
          head: main

      # Step 4: Print a helpful timestamp for your records (not required, just nice)
      - name: Timestamp
        run: date


