name: toc generator

on: [push,pull_request]

# https://github.com/technote-space/toc-generator#condition2
jobs:
  generateTOC:
    name: toc generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: "README.md"
          INCLUDE_LABELS: documentation
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREATE_PR: true
          CHECK_ONLY_DEFAULT_BRANCH: true
